# $Id: Makefile 2140 2011-11-10 14:27:03Z jkoshy $

TOP=	..

INCS=	elfdefinitions.h
INCSDIR?=	/usr/include

.PHONY:	all clean clobber depend obj

all depend obj:

clean clobber:
	rm -f ${CLEANFILES}

.include "${TOP}/mk/elftoolchain.inc.mk"
