/* WARNING: Generated by "make-toolchain-version". */

#include <sys/types.h>
#include <libelftc.h>

const char *
elftc_version(void)
{
	return "elftoolchain HEAD RTEMS git:heads/covoar-dwarf-0-g9b49665-dirty";
}
