#
# RTEMS Tools Project (http://www.rtems.org/)
# Copyright 2014, 2015 Chris Johns (chrisj@rtems.org)
# All rights reserved.
#
# This file is part of the RTEMS Tools package in 'rtems-tools'.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

#
# RTEMS Linker build script.
#
import sys

def init(ctx):
    pass

def options(opt):
    opt.load('compiler_c')
    opt.load('compiler_cxx')

def configure(conf):
    conf.load('compiler_c')
    conf.load('compiler_cxx')

    conf.write_config_header('config.h')

def build(bld):
    #
    # Build the doxygen documentation.
    #
    if bld.cmd == 'doxy':
        bld(features = 'doxygen',
            doxyfile = 'rtl-host.conf')
        return

    #
    # The local configuration.
    #
    conf = {}

    #
    # Build flags.
    #
    rtemstoolkit = '../rtemstoolkit'
    conf['includes'] = [rtemstoolkit,
                        rtemstoolkit + '/elftoolchain/libelf',
                        rtemstoolkit + '/elftoolchain/common',
                        rtemstoolkit + '/libiberty']
    if bld.env.DEST_OS == 'win32':
        conf['includes'] += [rtemstoolkit + '/win32']
    conf['warningflags'] = ['-Wall', '-Wextra', '-pedantic']
    conf['optflags'] = bld.env.C_OPTS
    conf['cflags'] = ['-pipe', '-g'] + conf['optflags']
    conf['cxxflags'] = ['-pipe', '-g'] + conf['optflags']
    conf['linkflags'] = ['-g']

    #
    # The list of modules.
    #
    modules = ['rld', 'elf', 'iberty']

    #
    # The list of defines
    #
    defines = ['HAVE_CONFIG_H=1',
               'RTEMS_VERSION=\"%s\"' % (bld.env.RTEMS_VERSION),
               'RTEMS_RELEASE=\"%s\"' % (bld.env.RTEMS_RELEASE)]

    #
    # Build the linker.
    #
    bld.program(target = 'rtems-ld',
                source = ['rtems-ld.cpp'],
                defines = defines,
                includes = ['.'] + conf['includes'],
                cflags = conf['cflags'] + conf['warningflags'],
                cxxflags = conf['cxxflags'] + conf['warningflags'],
                linkflags = conf['linkflags'],
                use = modules)

    #
    # Build the ra linker.
    #
    bld.program(target = 'rtems-ra',
                source = ['rtems-ra.cpp'],
                defines = defines,
                includes = ['.'] + conf['includes'],
                cflags = conf['cflags'] + conf['warningflags'],
                cxxflags = conf['cxxflags'] + conf['warningflags'],
                linkflags = conf['linkflags'],
                use = modules)

    #
    # Build the trace linker.
    #
    bld.program(target = 'rtems-tld',
                source = ['rtems-tld.cpp'],
                defines = defines,
                includes = ['.'] + conf['includes'],
                cflags = conf['cflags'] + conf['warningflags'],
                cxxflags = conf['cxxflags'] + conf['warningflags'],
                linkflags = conf['linkflags'],
                use = modules)
    bld.install_files('${PREFIX}/share/rtems/trace-linker',
                      ['libc.ini',
                       'libc-heap.ini',
                       'rtems.ini',
                       'rtems-api.ini',
                       'rtems-posix.ini',
                       'rtems-score.ini',
                       'rtems-score-object.ini',
                       'rtems-score-thread.ini',
                       'rtems-score-heap.ini',
                       'rtems-score-coremutex.ini',
                       'rtld-base.ini',
                       'rtld-trace-buffer.ini',
                       'rtld-print.ini'])

    #
    # Build the symbols.
    #
    bld.program(target = 'rtems-syms',
                source = ['rtems-syms.cpp'],
                defines = defines,
                includes = ['.'] + conf['includes'],
                cflags = conf['cflags'] + conf['warningflags'],
                cxxflags = conf['cxxflags'] + conf['warningflags'],
                linkflags = conf['linkflags'],
                use = modules)

    #
    # Build the RAP utility.
    #
    bld.program(target = 'rtems-rap',
                source = ['rtems-rapper.cpp'],
                defines = defines,
                includes = ['.'] + conf['includes'],
                cflags = conf['cflags'] + conf['warningflags'],
                cxxflags = conf['cxxflags'] + conf['warningflags'],
                linkflags = conf['linkflags'],
                use = modules)

def tags(ctx):
    ctx.exec_command('etags $(find . -name \*.[sSch])', shell = True)
